### ISSUE TITLE
[Feature/Search Page] ItemCard컴포넌트를 구현해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#10]
### Issues
Type: `feature`
Detail: Timer, Chat컴포넌트를 포함해야 합니다.

### Todo

1. [x] 상태 저장소에서 위치 정보를 받아와 표시해줘야합니다. -> search에서 해줄것
2. [x] 사진을 표시해야 합니다.
3. [x] Timer컴포넌트를 배치해야 합니다.
4. [x] CurrentPrice컴포넌트를 포함해야 합니다.
5. [x] Timer에서 받은 isExpired값을 통해 GoChat컴포넌트를 조건부 렌더링 해야합니다.

### Labels

- Estimated Time: `E: 3H`
- Urgency: `High`
