### ISSUE TITLE
[Feature/Landing Page] Landing Page컴포넌트를 구현해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#105]
### Issues
Type: `feature`
Detail: https://miro.com/app/board/o9J_lM9EiNA=/ 링크에서 구상한 랜딩 페이지를 참고해 구현해주세요

### Todo

1. [x] Start, Footer 컴포넌트가 포함되어야 합니다.
2. [x] 첫번재 색션에는 Start컴포넌트, gif 이미지가 들어가야 합니다. (gif 이미지는 시연 영상 촬영때 제작)
3. [x] 두번째 색션에는 검색페이지 이미지와 지도 이미지가 들어가야 합니다.
4. [x] 세번째 색션에는 물품등록 이미지와 Start컴포넌트가 들어가야 합니다.
5. [x] 마지막으로 Footer컴포넌트가 표시되어야 합니다.

### Labels

- Estimated Time: `E: 3H`
- Urgency: `High`
