### ISSUE TITLE
[Feature/Landing Page] Footer컴포넌트를 구현해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#106]
### Issues
Type: `feature`
Detail: https://miro.com/app/board/o9J_lM9EiNA=/ 에서 구성한 것을 참고해 구현해야 합니다.

### Todo

1. [x] 서비스 소개를 누르면 https://github.com/codestates/lilakchal-server 로 이동되어야 합니다.
2. [x] 팀원의 이름을 누르면 각 팀원의 개인 깃허브 페이지로 이동되어야 합니다.
3. [x] 유튜브 아이콘을 누르면 코드스테이츠 유튜브 채널로 이동되어야 합니다. (발표영상 업로드 이후 발표 영상으로 변경)
4. [x] CSS를 이용해 멋지게 꾸며주세요

### Labels

- Estimated Time: `E: 3H`
- Urgency: `High`
