### ISSUE TITLE
[Feature/Search Page] Timer컴포넌트를 구현해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#11]
### Issues
Type: `feature`
Detail: 서버 시간과 브라우저 시간의 차이를 통해 경매의 남은 시간을 표시해야 합니다.

### Todo

1. [x] ItemCard에서 입찰 마감 시간을 가져온다
2. [x] 브라우저 시간과 입찰 마감 시간의 차이를 계산 후 표시한다.
4. [x] setInterval을 이용해 2번의 값을 1초씩 줄인다.
6. [x] 타이머의 시간이 0 미만이 되면 isClosed 상태를 true로 변경해야 합니다. 상태는 ItemCard로 올려줘야 합니다.

### Labels

- Estimated Time: `E: 24H`
- Urgency: `Middle`
