### ISSUE TITLE
[Feature/Search Page] ItemDetail컴포넌트를 구현해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#12]
### Issues
Type: `feature`
Detail: BidBtn, Timer컴포넌트를 포함해야 합니다.

### Todo

1. [x] 등록된 물품의 정보를 표시해야 합니다.
2. [x] BidBtn컴포넌트를 1000원, 10000원, 100000원 단위의 3개를 표시해야 합니다.
3. [ ] BidBtn컴포넌트를 클릭한 경우 search에서 받아온 requestBid 메소드를 통해 변경된 입찰가격을 전달해야 합니다
4. [x] unit(입찰 가격 단위) 상태를 BidBtn으로 전달해야 합니다.
5. [x] Timer컴포넌트를 표시해야 합니다. CSS는 ItemCard의 시간과 다르게 꾸며져야 합니다.
6. [x] CurrentPrice컴포넌트를 포함해야 합니다.

### Labels

- Estimated Time: `E: 3H`
- Urgency: `High`
