### ISSUE TITLE
[Feature/Search Page] BidBtn컴포넌트를 구현해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#13]
### Issues
Type: `feature`
Detail:  버튼을 누르면 입찰가격을 ItemDtail컴포넌트에 전달해야 합니다.

### Todo

1. [x] ItemDetail컴포넌트에서 unit props를 받아와 입찰 가격 단위를 표시해야 합니다.
2. [ ] 버튼을 누르면 입찰가격을 ItemDtail컴포넌트에 전달해야 합니다.
3. [ ] BidBtn의 값을 쿼리셀렉트가 아닌 리덕스로 가져와야 합니다.

### Labels

- Estimated Time: `E: 3H`
- Urgency: `High`
