### ISSUE TITLE
[Bug/My Page] 검색 필터에 따라 받아오는 ItemCard 도시 표시 이슈

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#130]
### Issues
Type: `bug`
Detail: 

### Todo

1. [x] post myauction/buyer, myauction/seller 요청에 도시 정보도 보내줘야 합니다.
2. [x] 응답에 따라 도시를 표시해야 합니다.
3. [x] offset 6 기준으로 변경합니다.

### Labels

- Estimated Time: `E: 3H`
- Urgency: `High`
