### ISSUE TITLE
[Bug/Search Page] 반응형 무한 스크롤 수정

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#131]
### Issues
Type: `bug`
Detail: 모바일 환경에서 무한 스크롤이 작동되어야 합니다.

### Todo

1. [x] 모바일 환경에서 무한 스크롤이 작동되어야 합니다.
2. [x] 스크롤이 화면의 80% 정도에 도달했을때, 서버에 요청하게 합니다
3. [x] 서버로부터 응답을 받기 전에 여러번 요청을 하지 말아야 합니다.

### Labels

- Estimated Time: `E: 3H`
- Urgency: `High`
