### ISSUE TITLE
[Feature/Search Page] 모바일 반응형 HeaderIcons컴포넌트를 구현해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#133]
### Issues
Type: `feature`
Detail: 반응형으로 동작하는 HeaderIcons를 구현해야 합니다.

### Todo

1. [ ] 모달로 경매 등록, 등록한 경매, 입찰한 경매 기능으로 라우팅을 한다.
2. [ ] 로그인 상태, width에 따라 보여준다.
3. [ ] 아이콘을 눌렀을 때 모달창이 나오고 기능에 따라 라우팅해준다.
4. [ ] LoginSection에 GoMypage컴포넌트 자리에 같이 둔다.
5. [ ] width 380px 이하일때 GoMypage를 숨기고 만든 컴포넌트를 표시한다.
6. [ ] Header컴포넌트를 반응형으로 구현해야 합니다.

### Labels

- Estimated Time: `E: 3H`
- Urgency: `High`
