### ISSUE TITLE
[Feature/Search Page] Header컴포넌트의 CSS를 수정해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#136]
### Issues
Type: `feature`
Detail: 

### Todo

1. [x] 아이콘 컬러는 #4A5058로 한다.
2. [x] 검색 아이콘을 좀 더 얇은 돋보기 모양으로 변경한다.
2. [x] 마우스 호버 시 색상이 #4EBDC9로 변한다. (GoMyPage 아이콘, Logout 아이콘은 #FF7997로 변한다)
3. [x] 마우스 호버 시 아이콘이 커지지 않아야 합니다.
4. [x] 이름에 마우스가 호버되면 커서를 포인터로 바꾸고 색상은 그대로
5. [x] 검색창 양 옆으로 여백이 추가되어야 합니다.

### Labels

- Estimated Time: `E: 3H`
- Urgency: `Middle`
