### ISSUE TITLE
[Feature/Register Form] Register Form CSS를 수정해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#140]
### Issues
Type: `feature`
Detail: 

### Todo

1. [x] 제목 가격 기간 간격 축소
2. [x] 사진 등록 시 테두리 없애기
3. [x] 등록 버튼 밑에 여유 공간 남기기

### Labels

- Estimated Time: `E: 3H`
- Urgency: `Middle`
