### ISSUE TITLE
[Feature/Register Page] Header, Register Page 모바일 반응형 CSS 수정

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#151]
### Issues
Type: `feature`
Detail: 

### Todo

1. [ ] Header에 물품 등록 버튼이 모바일에서는 보이지 않아야 합니다.
2. [ ] 모바일에서 Register Page의 여백이 남아있어야 합니다.
3. [ ] SearchBar컴포넌트의 Placeholder 메시지 변경(맥북 -> 애플)
4. [ ] 헤더 아이콘 모달 컬러 변경

### Labels

- Estimated Time: `E: 3H`
- Urgency: `Low`
