### ISSUE TITLE
[Feature/CSS] 전체적인 디자인 점검

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#156]
### Issues
Type: `feature`
Detail: 

### Todo

1. [ ] 전체적인 CSS를 점검해주세요
2. [x] 경매 등록 페이지 반응형 구간 추가
3. [ ] 모바일 메뉴 색상 

### Labels

- Estimated Time: `E: 3H`
- Urgency: `High`
