### ISSUE TITLE
[Bug/Register Page] 최소 금액 제한 설정

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#164]
### Issues
Type: `bug`, `feature`, `etc`
Detail: 

### Todo

1. [x] 21억 이상의 금액을 최소가격으로 설정할 수 없게 해야 합니다
2. [x] title, description에 정규 표현식을 이용해 html태그를 작성할 수 없게 막아야 합니다.
3. [x] BidBtn 눌렀을 때 현재 가격이 21억이 넘었다면 버튼을 누를수 없게 해야 합니다.

### Labels

- Estimated Time: `E: 3H`
- Urgency: `High`
