### ISSUE TITLE
[Feature/Landing Page] Landing Page 반응형 구현

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#172]
### Issues
Type: `feature`
Detail: 

### Todo

1. [x] 두번째 섹션 모바일 화면 이미지 크기 조정
2. [x] 마지막 섹션 모바일 화면 이미지 크기 조정
2. [x] 글씨 크기 통일(1rem)

### Labels

- Estimated Time: `E: 3H`
- Urgency: `High`
