### ISSUE TITLE
[Feature/Register Page] RegisterForm컴포넌트를 구현해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#19]
### Issues
Type: `feature`
Detail: title, price, description, photo을 구현해야합니다

### Todo

1. [x] title, price, description, photo를 구현해야합니다.
2. [x] SubmitBtn컴포넌트를 포함해야 합니다.
4. [x] SubmitBtn에 submitHandler와 '등록'(str) 문자열을 props로 내려줘야 합니다.
5. [x] submitHandler함수가 실행되면 입력된 값으로 POST요청을 보내야 합니다.
5. [x] 기간을 선택할 수 있는 버튼 3개를 만들어야 합니다.(1일, 3일, 7일)
6. [x] 기간의 값은 현재 날짜 + 1일, 3일, 7일 이어야 합니다.
5. [x] 이미지를 photo(input)에 추가하면 이미지가 표시되어야 합니다
6. [x] description 은 textarea 태그를 이용해 구현해야합니다.

### Labels

- Estimated Time: `E: nH`
- Urgency: `High`
