### ISSUE TITLE
[Refactoring/Optimization] Loading Modal 의존성 제거

### ISSUE THREAD

**Issue by ImHyeLim1209** [codestates/lilakchal-client#208]
### Issues
Type: `Refactoring`
Detail: 

### Todo

1. [x] Loading Modal의 GeoLocation 로직 분리 및 props로 받기
2. [x] Suspense의 Fallback에 Loading Modal 추가
3. [x] Search 페이지 외에는 지역찾지 않도록 수정

### Labels

- Estimated Time: `E: 3H`
- Urgency: `Middle`
