### ISSUE TITLE
[Feature/Register Page] SubmitBtn컴포넌트를 구현해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#21]
### Issues
Type: `feature`
Detail: '등록'(str) 문자열과 submitHandler함수를 RegisterForm컴포넌트에서 받아와야 합니다

### Todo

- [x] '등록' 문자열과 submitHandler함수를 RegisterForm컴포넌트에서 받아와야 합니다.
- [x] 버튼의 textContent는 str이어야 합니다.
- [x] 버튼을 클릭하면 submitHandler함수를 실행해야 합니다.

### Labels

- Estimated Time: `E: 3H`
- Urgency: `High`
