### ISSUE TITLE
[Refactoring/Optimization] CSS 점검

### ISSUE THREAD

**Issue by ImHyeLim1209** [codestates/lilakchal-client#211]
### Issues
Type: `Refactoring`
Detail: 

### Todo

1. [x] 공통된 style mixin 추가
2. [x] animation translate를 translate3D로 변경
3. [x] handler 함수 이름 수정(function = handle, property = handler)

### Labels

- Estimated Time: `E: 1H`
- Urgency: `Middle`
