### ISSUE TITLE
[Feature/My Page] FilterBtn컴포넌트를 구현해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#23]
### Issues
Type: `feature`
Detail: 등록, 입찰에 따른 요청을 보내야 합니다.

### Todo

1. [ ] 필터 아이콘 클릭 시 등록, 입찰창이 열린 상태로 유지되어야 합니다, 다시 누르면 닫혀야 합니다.
2. [x] 등록, 입찰에 따른 요청을 보내야 합니다.
3. [x] 요청에 따른 결과를 상태 저장소에 저장해야합니다.
4. [x] 등록을 누르면 /mypage/register로 라우팅 되어야 합니다.
5. [x] 입찰을 누르면 /mypage/bid로 라우팅 되어야 합니다.
6. [x] 마이페이지 -> 뒤로가기 -> 앞으로가기 순서로 눌렀을 때 마이페이지의 헤더가 변경되어야 합니다.

### Labels

- Estimated Time: `E: 3H`
- Urgency: `High`
