### ISSUE TITLE
[Feature/My Page] Message컴포넌트를 구현해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#28]
### Issues
Type: `feature`
Detail: msg를 Message에 표시해야 합니다.

### Todo

1. [ ] Chat페이지에서 isMine, msg props를 받아와야 합니다
2. [ ] isMine에 따라 다른 CSS가 적용되어야 합니다.
3. [ ] meg를 Message div 안에 표시해야 합니다.

### Labels

- Estimated Time: `E: 3H`
- Urgency: `High`
