### ISSUE TITLE
[Feature/My Page] UserName컴포넌트를 구현해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#31]
### Issues
Type: `feature`
Detail: 

### Todo

1. [x] button 태그를 포함해야 합니다
2. [x] button을 누르면 EditForm컴포넌트가 포함된 modal이 표시되어야 합니다.
3. [x] EditFrom에서 사용자의 이름이 변경될 경우 변경된 이름을 상태 저장소에서 가져와야 합니다.
4. [x] 가져온 이름을 표시해야 합니다.

### Labels

- Estimated Time: `E: 3H`
- Urgency: `Middle`
