### ISSUE TITLE
[Feature/Search Page] AuctionFilter컴포넌트를 구현해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#5]
### Issues
Type: `feature`
Detail: 등록한 경매, 입찰한 경매를 구분할 수 있는 필터를 만들어야 합니다.

### Todo

1. [x] MyOptionGroup컴포넌트에서 setAuctionType 메소드와 auctionType state를받아 메소드를 이용해 state를 변경한다.
2. [x] state가 변경된 값을 Header로 전달한다
3. [x] 전달한 값에 따라 filter가 변경되 보여야 한다.

### Labels

- Estimated Time: `3: nH`
- Urgency: `High`
