### ISSUE TITLE
[Bug/Search Page] SearchBar 버그 수정

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#52]
### Issues
Type: `bug`
Detail: 

### Todo

1. [x] SearchBar.tsx '도시' 리덕스의 city로 교체
2. [x] 검색 후 뒤로가기 했을때 이전 검색 결과가 보여야합니다.
3. [x] 엔터 누르면 검색되게 만들기

### Labels

- Estimated Time: `E: 3H`
- Urgency: `Middle`
