### ISSUE TITLE
[Bug/Search Page] 물품 등록 시 등록한 사람 id 같이 보내기

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#54]
### Issues
Type: `bug`
Detail: 

### Todo

1. [x] 물품 등록 시 등록한 사람 id 같이 보내기
2. [x] 비회원 물품등록, 입찰 누를 시 경고문 띄우기
3. [x] 닉네임 변경 버그 수정

### Labels

- Estimated Time: `E: 3H`
- Urgency: `Middle`
