### ISSUE TITLE
[Feature/My Page] MyOptionGroup 컴포넌트를 구현해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#6]
### Issues
Type: `feature`
Detail: MyOptionGroup에는 FilterBtn 컴포넌트가 포함되어있습니다.

### Todo

1. [x] 상태 저장소에서 auctionType state를받아 FilterBtn컴포넌트로 넘겨줘야 합니다.
2. [x] FilterBtn 컴포넌트가 포함되어있습니다.
3. [x] logoutBtn을 클릭하면 서버에 로그아웃 요청을 보내고 isLogin이 false로 변경되며 렌딩페이지로 이동 되어야 합니다
4. [x] GoSearch을 클릭하면 /search로 라우팅 되어야 합니다.
5. [x] UserName 컴포넌트가 포함되어야 합니다.

### Labels

- Estimated Time: `E: nH`
- Urgency: `High`
