### ISSUE TITLE
[Feature/Search Page] Loading컴포넌트를 수정해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#70]
### Issues
Type: `feature`
Detail: 

### Todo

1. [x] Loading 컴포넌트에서 위치를 찾아야 합니다.
2. [x] 찾은 위치를 리덕스에 저장해야 합니다.
3. [x] 리덕스에 저장된 위치값이 존재하면 Loading컴포넌트가 표시되지 않아야 합니다.

### Labels

- Estimated Time: `E: 3H`
- Urgency: `High`
