### ISSUE TITLE
[Feature/Search Page] Header컴포넌트를 구현해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#8]
### Issues
Type: `feature`
Detail: 라우팅에 따라 컴포넌트를 배치해줘야 합니다.

### Todo

1. [x] /mypage로 라우팅 되는 경우 MyOptionGroup컴포넌트를 렌더링 해야 합니다.
2. [x] /search, /register로 라우팅 되는 경우 DefaultGroup컴포넌트를 렌더링 해야 합니다.
3. [x] 로고를 클릭한 경우 '/'(렌딩페이지)로 라우팅 되어야 합니다.

### Labels

- Estimated Time: `E: 3H`
- Urgency: `High`
