### ISSUE TITLE
[Feature/SearchPage] 검색 결과가 없을 경우 보여줄 Empty 컴포넌트를 구현해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#80]
### Issues
Type: `feature`
Detail: 

### Todo

1. [x] Empty컴포넌트를 구현해야 합니다.
2. [x] 검색 결과가 없을 경우에만 표시되어야 합니다.
3. [x] 결과 없음을 의미하는 텍스트와 이미지가 포함되어야 합니다.

### Labels

- Estimated Time: `E: 3H`
- Urgency: `Middle`
