### ISSUE TITLE
[Feature/Search Page] Search페이지를 구현해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/lilakchal-client#9]
### Issues
Type: `feature`
Detail: ItemCard, ItemDetail컴포넌트를 포함하고 있어야 합니다.

### Todo

1. [x] ItemCard를 클릭한 경우 ItemDetail컴포넌트를 모달로 표현해야 합니다.
2. [x] ItemCard를 map메소드로 나열해서 보여줘야 합니다.
3. [x] isConnet상태에 따라 socket.io에 연결해야 합니다.
4. [x] bid이벤트에 파라미터로 들어있는 itemId와 price를 쿼리셀렉터를 사용해 가격 부분만 다시 렌더링 한다.
5. [x] ItemDetail컴포넌트에 socket.io로 메세지를 보낼 수 있는 requestBid 메소드를 전달해야 합니다. -> ItemCard로 변경
6. [ ] 키워드를 리덕스에서 받고 아이템 개수를 계산해(초기값은 0) 검색 요청을 보내며 무한 스크롤을 구현해야 합니다.
7. [x] 사용자에게 위치정보 이용 동의 요청을 보내야 합니다.

### Labels

- Estimated Time: `E: 3H`
- Urgency: `High`
